package tr.xip.prayertimes.api;

import java.util.ArrayList;
import java.util.List;

import tr.xip.prayertimes.api.objects.Country;

public class ApiResources {

    public static List<Country> getCountriesList() {
        List<Country> mCountriesList = new ArrayList<>();
        mCountriesList.add(new Country("33", "ABD"));
        mCountriesList.add(new Country("166", "AFGANISTAN"));
        mCountriesList.add(new Country("13", "ALMANYA"));
        mCountriesList.add(new Country("17", "ANDORRA"));
        mCountriesList.add(new Country("140", "ANGOLA"));
        mCountriesList.add(new Country("125", "ANGUILLA"));
        mCountriesList.add(new Country("90", "ANTIGUA VE BARBUDA"));
        mCountriesList.add(new Country("199", "ARJANTIN"));
        mCountriesList.add(new Country("25", "ARNAVUTLUK"));
        mCountriesList.add(new Country("153", "ARUBA"));
        mCountriesList.add(new Country("59", "AVUSTRALYA"));
        mCountriesList.add(new Country("35", "AVUSTURYA"));
        mCountriesList.add(new Country("5", "AZERBAYCAN"));
        mCountriesList.add(new Country("54", "BAHAMALAR"));
        mCountriesList.add(new Country("132", "BAHREYN"));
        mCountriesList.add(new Country("177", "BANGLADES"));
        mCountriesList.add(new Country("188", "BARBADOS"));
        mCountriesList.add(new Country("208", "BELARUS"));
        mCountriesList.add(new Country("11", "BELCIKA"));
        mCountriesList.add(new Country("182", "BELIZE"));
        mCountriesList.add(new Country("181", "BENIN"));
        mCountriesList.add(new Country("51", "BERMUDA"));
        mCountriesList.add(new Country("93", "BIRLESIK ARAP EMIRLIGI"));
        mCountriesList.add(new Country("83", "BOLIVYA"));
        mCountriesList.add(new Country("9", "BOSNA HERSEK"));
        mCountriesList.add(new Country("167", "BOTSVANA"));
        mCountriesList.add(new Country("146", "BREZILYA"));
        mCountriesList.add(new Country("97", "BRUNEI"));
        mCountriesList.add(new Country("44", "BULGARISTAN"));
        mCountriesList.add(new Country("91", "BURKINA FASO"));
        mCountriesList.add(new Country("154", "BURMA (MYANMAR)"));
        mCountriesList.add(new Country("65", "BURUNDI"));
        mCountriesList.add(new Country("155", "BUTAN"));
        mCountriesList.add(new Country("156", "CAD"));
        mCountriesList.add(new Country("43", "CECENISTAN"));
        mCountriesList.add(new Country("16", "CEK CUMHURIYETI"));
        mCountriesList.add(new Country("86", "CEZAYIR"));
        mCountriesList.add(new Country("160", "CIBUTI"));
        mCountriesList.add(new Country("61", "CIN"));
        mCountriesList.add(new Country("26", "DANIMARKA"));
        mCountriesList.add(new Country("180", "DEMOKRATIK KONGO CUMHURIYETI"));
        mCountriesList.add(new Country("176", "DOGU TIMOR"));
        mCountriesList.add(new Country("123", "DOMINIK"));
        mCountriesList.add(new Country("72", "DOMINIK CUMHURIYETI"));
        mCountriesList.add(new Country("139", "EKVATOR"));
        mCountriesList.add(new Country("63", "EKVATOR GINESI"));
        mCountriesList.add(new Country("165", "EL SALVADOR"));
        mCountriesList.add(new Country("117", "ENDONEZYA"));
        mCountriesList.add(new Country("175", "ERITRE"));
        mCountriesList.add(new Country("104", "ERMENISTAN"));
        mCountriesList.add(new Country("6", "ESTONYA"));
        mCountriesList.add(new Country("95", "ETYOPYA"));
        mCountriesList.add(new Country("145", "FAS"));
        mCountriesList.add(new Country("197", "FIJI"));
        mCountriesList.add(new Country("120", "FILDISI SAHILI"));
        mCountriesList.add(new Country("126", "FILIPINLER"));
        mCountriesList.add(new Country("204", "FILISTIN"));
        mCountriesList.add(new Country("41", "FINLANDIYA"));
        mCountriesList.add(new Country("21", "FRANSA"));
        mCountriesList.add(new Country("79", "GABON"));
        mCountriesList.add(new Country("109", "GAMBIYA"));
        mCountriesList.add(new Country("143", "GANA"));
        mCountriesList.add(new Country("111", "GINE"));
        mCountriesList.add(new Country("58", "GRANADA"));
        mCountriesList.add(new Country("48", "GRONLAND"));
        mCountriesList.add(new Country("171", "GUADELOPE"));
        mCountriesList.add(new Country("169", "GUAM ADASI"));
        mCountriesList.add(new Country("99", "GUATEMALA"));
        mCountriesList.add(new Country("67", "GUNEY AFRIKA"));
        mCountriesList.add(new Country("128", "GUNEY KORE"));
        mCountriesList.add(new Country("62", "GURCISTAN"));
        mCountriesList.add(new Country("82", "GUYANA"));
        mCountriesList.add(new Country("70", "HAITI"));
        mCountriesList.add(new Country("187", "HINDISTAN"));
        mCountriesList.add(new Country("30", "HIRVATISTAN"));
        mCountriesList.add(new Country("4", "HOLLANDA"));
        mCountriesList.add(new Country("66", "HOLLANDA ANTILLERI"));
        mCountriesList.add(new Country("105", "HONDURAS"));
        mCountriesList.add(new Country("113", "HONG KONG"));
        mCountriesList.add(new Country("15", "INGILTERE"));
        mCountriesList.add(new Country("124", "IRAK"));
        mCountriesList.add(new Country("202", "IRAN"));
        mCountriesList.add(new Country("32", "IRLANDA"));
        mCountriesList.add(new Country("23", "ISPANYA"));
        mCountriesList.add(new Country("205", "ISRAIL"));
        mCountriesList.add(new Country("12", "ISVEC"));
        mCountriesList.add(new Country("49", "ISVICRE"));
        mCountriesList.add(new Country("8", "ITALYA"));
        mCountriesList.add(new Country("122", "IZLANDA"));
        mCountriesList.add(new Country("119", "JAMAIKA"));
        mCountriesList.add(new Country("116", "JAPONYA"));
        mCountriesList.add(new Country("161", "KAMBOCYA"));
        mCountriesList.add(new Country("184", "KAMERUN"));
        mCountriesList.add(new Country("52", "KANADA"));
        mCountriesList.add(new Country("34", "KARADAG"));
        mCountriesList.add(new Country("94", "KATAR"));
        mCountriesList.add(new Country("92", "KAZAKISTAN"));
        mCountriesList.add(new Country("114", "KENYA"));
        mCountriesList.add(new Country("168", "KIRGIZISTAN"));
        mCountriesList.add(new Country("57", "KOLOMBIYA"));
        mCountriesList.add(new Country("88", "KOMORLAR"));
        mCountriesList.add(new Country("18", "KOSOVA"));
        mCountriesList.add(new Country("162", "KOSTARIKA"));
        mCountriesList.add(new Country("209", "KUBA"));
        mCountriesList.add(new Country("206", "KUDUS"));
        mCountriesList.add(new Country("133", "KUVEYT"));
        mCountriesList.add(new Country("1", "KUZEY KIBRIS"));
        mCountriesList.add(new Country("142", "KUZEY KORE"));
        mCountriesList.add(new Country("134", "LAOS"));
        mCountriesList.add(new Country("174", "LESOTO"));
        mCountriesList.add(new Country("20", "LETONYA"));
        mCountriesList.add(new Country("73", "LIBERYA"));
        mCountriesList.add(new Country("203", "LIBYA"));
        mCountriesList.add(new Country("38", "LIECHTENSTEIN"));
        mCountriesList.add(new Country("47", "LITVANYA"));
        mCountriesList.add(new Country("42", "LUBNAN"));
        mCountriesList.add(new Country("31", "LUKSEMBURG"));
        mCountriesList.add(new Country("7", "MACARISTAN"));
        mCountriesList.add(new Country("98", "MADAGASKAR"));
        mCountriesList.add(new Country("100", "MAKAO"));
        mCountriesList.add(new Country("28", "MAKEDONYA"));
        mCountriesList.add(new Country("55", "MALAVI"));
        mCountriesList.add(new Country("103", "MALDIVLER"));
        mCountriesList.add(new Country("107", "MALEZYA"));
        mCountriesList.add(new Country("152", "MALI"));
        mCountriesList.add(new Country("24", "MALTA"));
        mCountriesList.add(new Country("87", "MARTINIK"));
        mCountriesList.add(new Country("164", "MAURITIUS ADASI"));
        mCountriesList.add(new Country("157", "MAYOTTE"));
        mCountriesList.add(new Country("53", "MEKSIKA"));
        mCountriesList.add(new Country("85", "MIKRONEZYA"));
        mCountriesList.add(new Country("189", "MISIR"));
        mCountriesList.add(new Country("60", "MOGOLISTAN"));
        mCountriesList.add(new Country("46", "MOLDAVYA"));
        mCountriesList.add(new Country("3", "MONAKO"));
        mCountriesList.add(new Country("147", "MONTSERRAT (U.K.)"));
        mCountriesList.add(new Country("106", "MORITANYA"));
        mCountriesList.add(new Country("151", "MOZAMBIK"));
        mCountriesList.add(new Country("196", "NAMBIYA"));
        mCountriesList.add(new Country("76", "NEPAL"));
        mCountriesList.add(new Country("84", "NIJER"));
        mCountriesList.add(new Country("127", "NIJERYA"));
        mCountriesList.add(new Country("141", "NIKARAGUA"));
        mCountriesList.add(new Country("178", "NIUE"));
        mCountriesList.add(new Country("36", "NORVEC"));
        mCountriesList.add(new Country("80", "ORTA AFRIKA CUMHURIYETI"));
        mCountriesList.add(new Country("131", "OZBEKISTAN"));
        mCountriesList.add(new Country("77", "PAKISTAN"));
        mCountriesList.add(new Country("149", "PALAU"));
        mCountriesList.add(new Country("89", "PANAMA"));
        mCountriesList.add(new Country("185", "PAPUA YENI GINE"));
        mCountriesList.add(new Country("194", "PARAGUAY"));
        mCountriesList.add(new Country("69", "PERU"));
        mCountriesList.add(new Country("183", "PITCAIRN ADASI"));
        mCountriesList.add(new Country("39", "POLONYA"));
        mCountriesList.add(new Country("45", "PORTEKIZ"));
        mCountriesList.add(new Country("68", "PORTO RIKO"));
        mCountriesList.add(new Country("112", "REUNION"));
        mCountriesList.add(new Country("37", "ROMANYA"));
        mCountriesList.add(new Country("81", "RUANDA"));
        mCountriesList.add(new Country("207", "RUSYA"));
        mCountriesList.add(new Country("198", "SAMOA"));
        mCountriesList.add(new Country("102", "SENEGAL"));
        mCountriesList.add(new Country("138", "SEYSEL ADALARI"));
        mCountriesList.add(new Country("200", "SILI"));
        mCountriesList.add(new Country("179", "SINGAPUR"));
        mCountriesList.add(new Country("27", "SIRBISTAN"));
        mCountriesList.add(new Country("14", "SLOVAKYA"));
        mCountriesList.add(new Country("19", "SLOVENYA"));
        mCountriesList.add(new Country("150", "SOMALI"));
        mCountriesList.add(new Country("74", "SRI LANKA"));
        mCountriesList.add(new Country("129", "SUDAN"));
        mCountriesList.add(new Country("172", "SURINAM"));
        mCountriesList.add(new Country("191", "SURIYE"));
        mCountriesList.add(new Country("64", "SUUDI ARABISTAN"));
        mCountriesList.add(new Country("163", "SVALBARD"));
        mCountriesList.add(new Country("170", "SVAZILAND"));
        mCountriesList.add(new Country("101", "TACIKISTAN"));
        mCountriesList.add(new Country("110", "TANZANYA"));
        mCountriesList.add(new Country("137", "TAYLAND"));
        mCountriesList.add(new Country("108", "TAYVAN"));
        mCountriesList.add(new Country("71", "TOGO"));
        mCountriesList.add(new Country("130", "TONGA"));
        mCountriesList.add(new Country("96", "TRINIDAT VE TOBAGO"));
        mCountriesList.add(new Country("118", "TUNUS"));
        mCountriesList.add(new Country("2", "TURKIYE"));
        mCountriesList.add(new Country("159", "TURKMENISTAN"));
        mCountriesList.add(new Country("75", "UGANDA"));
        mCountriesList.add(new Country("40", "UKRAYNA"));
        mCountriesList.add(new Country("29", "UKRAYNA-KIRIM"));
        mCountriesList.add(new Country("173", "UMMAN"));
        mCountriesList.add(new Country("192", "URDUN"));
        mCountriesList.add(new Country("201", "URUGUAY"));
        mCountriesList.add(new Country("56", "VANUATU"));
        mCountriesList.add(new Country("10", "VATIKAN"));
        mCountriesList.add(new Country("186", "VENEZUELA"));
        mCountriesList.add(new Country("135", "VIETNAM"));
        mCountriesList.add(new Country("148", "YEMEN"));
        mCountriesList.add(new Country("115", "YENI KALEDONYA"));
        mCountriesList.add(new Country("193", "YENI ZELLANDA"));
        mCountriesList.add(new Country("144", "YESIL BURUN"));
        mCountriesList.add(new Country("22", "YUNANISTAN"));
        mCountriesList.add(new Country("158", "ZAMBIYA"));
        mCountriesList.add(new Country("136", "ZIMBABVE"));
        return mCountriesList;
    }
}