package tr.xip.prayertimes.client

import tr.xip.prayertimes.model.Country
import kotlin.collections.listOf

object ClientResources {
    val COUNTRIES: List<Country> = listOf(
            Country("33", "ABD"),
            Country("166", "AFGANISTAN"),
            Country("13", "ALMANYA"),
            Country("17", "ANDORRA"),
            Country("140", "ANGOLA"),
            Country("125", "ANGUILLA"),
            Country("90", "ANTIGUA VE BARBUDA"),
            Country("199", "ARJANTIN"),
            Country("25", "ARNAVUTLUK"),
            Country("153", "ARUBA"),
            Country("59", "AVUSTRALYA"),
            Country("35", "AVUSTURYA"),
            Country("5", "AZERBAYCAN"),
            Country("54", "BAHAMALAR"),
            Country("132", "BAHREYN"),
            Country("177", "BANGLADES"),
            Country("188", "BARBADOS"),
            Country("208", "BELARUS"),
            Country("11", "BELCIKA"),
            Country("182", "BELIZE"),
            Country("181", "BENIN"),
            Country("51", "BERMUDA"),
            Country("93", "BIRLESIK ARAP EMIRLIGI"),
            Country("83", "BOLIVYA"),
            Country("9", "BOSNA HERSEK"),
            Country("167", "BOTSVANA"),
            Country("146", "BREZILYA"),
            Country("97", "BRUNEI"),
            Country("44", "BULGARISTAN"),
            Country("91", "BURKINA FASO"),
            Country("154", "BURMA (MYANMAR)"),
            Country("65", "BURUNDI"),
            Country("155", "BUTAN"),
            Country("156", "CAD"),
            Country("43", "CECENISTAN"),
            Country("16", "CEK CUMHURIYETI"),
            Country("86", "CEZAYIR"),
            Country("160", "CIBUTI"),
            Country("61", "CIN"),
            Country("26", "DANIMARKA"),
            Country("180", "DEMOKRATIK KONGO CUMHURIYETI"),
            Country("176", "DOGU TIMOR"),
            Country("123", "DOMINIK"),
            Country("72", "DOMINIK CUMHURIYETI"),
            Country("139", "EKVATOR"),
            Country("63", "EKVATOR GINESI"),
            Country("165", "EL SALVADOR"),
            Country("117", "ENDONEZYA"),
            Country("175", "ERITRE"),
            Country("104", "ERMENISTAN"),
            Country("6", "ESTONYA"),
            Country("95", "ETYOPYA"),
            Country("145", "FAS"),
            Country("197", "FIJI"),
            Country("120", "FILDISI SAHILI"),
            Country("126", "FILIPINLER"),
            Country("204", "FILISTIN"),
            Country("41", "FINLANDIYA"),
            Country("21", "FRANSA"),
            Country("79", "GABON"),
            Country("109", "GAMBIYA"),
            Country("143", "GANA"),
            Country("111", "GINE"),
            Country("58", "GRANADA"),
            Country("48", "GRONLAND"),
            Country("171", "GUADELOPE"),
            Country("169", "GUAM ADASI"),
            Country("99", "GUATEMALA"),
            Country("67", "GUNEY AFRIKA"),
            Country("128", "GUNEY KORE"),
            Country("62", "GURCISTAN"),
            Country("82", "GUYANA"),
            Country("70", "HAITI"),
            Country("187", "HINDISTAN"),
            Country("30", "HIRVATISTAN"),
            Country("4", "HOLLANDA"),
            Country("66", "HOLLANDA ANTILLERI"),
            Country("105", "HONDURAS"),
            Country("113", "HONG KONG"),
            Country("15", "INGILTERE"),
            Country("124", "IRAK"),
            Country("202", "IRAN"),
            Country("32", "IRLANDA"),
            Country("23", "ISPANYA"),
            Country("205", "ISRAIL"),
            Country("12", "ISVEC"),
            Country("49", "ISVICRE"),
            Country("8", "ITALYA"),
            Country("122", "IZLANDA"),
            Country("119", "JAMAIKA"),
            Country("116", "JAPONYA"),
            Country("161", "KAMBOCYA"),
            Country("184", "KAMERUN"),
            Country("52", "KANADA"),
            Country("34", "KARADAG"),
            Country("94", "KATAR"),
            Country("92", "KAZAKISTAN"),
            Country("114", "KENYA"),
            Country("168", "KIRGIZISTAN"),
            Country("57", "KOLOMBIYA"),
            Country("88", "KOMORLAR"),
            Country("18", "KOSOVA"),
            Country("162", "KOSTARIKA"),
            Country("209", "KUBA"),
            Country("206", "KUDUS"),
            Country("133", "KUVEYT"),
            Country("1", "KUZEY KIBRIS"),
            Country("142", "KUZEY KORE"),
            Country("134", "LAOS"),
            Country("174", "LESOTO"),
            Country("20", "LETONYA"),
            Country("73", "LIBERYA"),
            Country("203", "LIBYA"),
            Country("38", "LIECHTENSTEIN"),
            Country("47", "LITVANYA"),
            Country("42", "LUBNAN"),
            Country("31", "LUKSEMBURG"),
            Country("7", "MACARISTAN"),
            Country("98", "MADAGASKAR"),
            Country("100", "MAKAO"),
            Country("28", "MAKEDONYA"),
            Country("55", "MALAVI"),
            Country("103", "MALDIVLER"),
            Country("107", "MALEZYA"),
            Country("152", "MALI"),
            Country("24", "MALTA"),
            Country("87", "MARTINIK"),
            Country("164", "MAURITIUS ADASI"),
            Country("157", "MAYOTTE"),
            Country("53", "MEKSIKA"),
            Country("85", "MIKRONEZYA"),
            Country("189", "MISIR"),
            Country("60", "MOGOLISTAN"),
            Country("46", "MOLDAVYA"),
            Country("3", "MONAKO"),
            Country("147", "MONTSERRAT (U.K.)"),
            Country("106", "MORITANYA"),
            Country("151", "MOZAMBIK"),
            Country("196", "NAMBIYA"),
            Country("76", "NEPAL"),
            Country("84", "NIJER"),
            Country("127", "NIJERYA"),
            Country("141", "NIKARAGUA"),
            Country("178", "NIUE"),
            Country("36", "NORVEC"),
            Country("80", "ORTA AFRIKA CUMHURIYETI"),
            Country("131", "OZBEKISTAN"),
            Country("77", "PAKISTAN"),
            Country("149", "PALAU"),
            Country("89", "PANAMA"),
            Country("185", "PAPUA YENI GINE"),
            Country("194", "PARAGUAY"),
            Country("69", "PERU"),
            Country("183", "PITCAIRN ADASI"),
            Country("39", "POLONYA"),
            Country("45", "PORTEKIZ"),
            Country("68", "PORTO RIKO"),
            Country("112", "REUNION"),
            Country("37", "ROMANYA"),
            Country("81", "RUANDA"),
            Country("207", "RUSYA"),
            Country("198", "SAMOA"),
            Country("102", "SENEGAL"),
            Country("138", "SEYSEL ADALARI"),
            Country("200", "SILI"),
            Country("179", "SINGAPUR"),
            Country("27", "SIRBISTAN"),
            Country("14", "SLOVAKYA"),
            Country("19", "SLOVENYA"),
            Country("150", "SOMALI"),
            Country("74", "SRI LANKA"),
            Country("129", "SUDAN"),
            Country("172", "SURINAM"),
            Country("191", "SURIYE"),
            Country("64", "SUUDI ARABISTAN"),
            Country("163", "SVALBARD"),
            Country("170", "SVAZILAND"),
            Country("101", "TACIKISTAN"),
            Country("110", "TANZANYA"),
            Country("137", "TAYLAND"),
            Country("108", "TAYVAN"),
            Country("71", "TOGO"),
            Country("130", "TONGA"),
            Country("96", "TRINIDAT VE TOBAGO"),
            Country("118", "TUNUS"),
            Country("2", "TURKIYE"),
            Country("159", "TURKMENISTAN"),
            Country("75", "UGANDA"),
            Country("40", "UKRAYNA"),
            Country("29", "UKRAYNA-KIRIM"),
            Country("173", "UMMAN"),
            Country("192", "URDUN"),
            Country("201", "URUGUAY"),
            Country("56", "VANUATU"),
            Country("10", "VATIKAN"),
            Country("186", "VENEZUELA"),
            Country("135", "VIETNAM"),
            Country("148", "YEMEN"),
            Country("115", "YENI KALEDONYA"),
            Country("193", "YENI ZELLANDA"),
            Country("144", "YESIL BURUN"),
            Country("22", "YUNANISTAN"),
            Country("158", "ZAMBIYA"),
            Country("136", "ZIMBABVE")
    )
}